<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * DogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogRepository extends \Doctrine\ORM\EntityRepository
{
	public function dogsByUser(){

		return $this->CreateQueryBuilder('dogs');
						
		   }
				//->select('user.dogs');
}
